import Head from "next/head";
import { BiUserPlus } from "react-icons/bi";
import Form from "../components/form";
import Table from "../components/table";
import { useDispatch, useSelector } from "react-redux";
import { toggleChangeAction } from "../redux/reducer";

export default function Home() {
  const visible = useSelector((state) => state.crudapp.client.toggleForm);
  const dispatch = useDispatch();

  const onClickAddEmployee = () => {
    dispatch(toggleChangeAction());
  };

  return (
    <section>
      <Head>
        <title>CRUD Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="py-5 px-20">
        <h1 className="text-xl md:text-5xl text-center font-bold py-10">
          Employee Managemant
        </h1>
        <div className="container mx-auto flex justify-between py-5 border-b">
          <div className="left flex gap-3">
            <button
              onClick={onClickAddEmployee}
              className="flex bg-indigo-500 text-white px-4 py-2 border rounded-md hover:bg-gray-500 hover:border-indigo-500 hover:text-gray-800-500"
            >
              Add Employee
              <span className="px-1">
                <BiUserPlus size={23}></BiUserPlus>
              </span>
            </button>
          </div>
        </div>

        {/* Collapsable Form */}
        {visible ? <Form></Form> : <></>}

        {/* Table */}
        <div className="container mx-auto">
          <Table></Table>
        </div>
      </main>
    </section>
  );
}
